### ISSUE TITLE
Just have to praise your work in this ticket

### ISSUE THREAD

**Issue by BerndGewehr** [markewallace/verse-watsonwork#1]
Hi Mark, this is a really great example of adding useful custom verse mail actions. Love the node.js style of your project.

It specially motivates me to try the following:

- post a Verse mail as Connections todo item into one of my activities and select me or someone else who should do it
- use the mail subject as the title of the todo
- use the mail body as description of the todo
- transfer all attachments as attachments of the  todo
- use kudos Boards for this purpose if available

Again, thank you for the inspiration...

**Comment by markewallace** [comment]
Thanks @BerndGewehr. We are planning to do a more complete version of this with documentation . We're setting up a new organisation on GitHub specifically for Verse to collect this and other samples. Looking forward to hearing how you get on with your extension.
